### ISSUE TITLE
Suggestion to use the more general "Pen" protocol

### ISSUE THREAD

**Issue by justvanrossum** [simoncozens/beziers.py#1]
Here are just some suggestions, triggered by reading
https://github.com/simoncozens/beziers.py/blob/d1c65e11487ee36289b644a75cfe50adfbba78c5/beziers/path/__init__.py#L95

A super useful and reusable way of factoring is:

- have a Pen object (conforming to `fontTools.pens.basePen.AbstractBasePen`, possibly subclassing `BasePen` from the same module) to construct your Path instance
- have a `draw(pen)` method on your path so it can draw itself onto any other pen that conforms to the Pen protocol

Together this is way more versatile than interfacing with a fonttools Glyph object.

It would also allow you to cleanly factor out creating Matplot Path objects, as that could be a Pen, too, ready to be reused in *any* other context that supports Pens.

**Comment by justvanrossum** [comment]
Oh, and consider using 4 spaces for indentation. It's what everybody uses and makes seeing the code structure at a glance so much easier.

**Comment by justvanrossum** [comment]
> possibly subclassing BasePen

...or just subclass `DecomposingRecordingPen`, since you're already using that. Just add a method or property to build and return your `BezierPath` object.

**Comment by simoncozens** [comment]
One of the reasons why I started a new Bezier handling library was to get away from the Pen protocol. :-)

**Comment by justvanrossum** [comment]
Oh wow, what did the pen protocol ever do to you? :)

Joking aside, you're already using it internally (it made getting outlines from fonttools quite easy, no?), all I'm suggesting is to expose it, making your awesome looking library instantly way more easy to interface with for a lot of people.

Would you accept a PR?

**Comment by simoncozens** [comment]
The problem I have with the Pen interface is that it forces you to operate in a particular low-level way (methods implementing move/curve/line instructions on individual points) which may not be the best way to solve your problem; when manipulating curves you often want to work at a higher level, for example in terms of segments. So all I am doing in `fromFontToolsGlyph` is saying to the Pen object, "just give me the list of points, let me handle this!"

Compatibility with other libraries is a very good thing and I'd be very happy to take a PR.

One of the ideas for Beziers.py is that it should be able to consume and emit curve representations from other libraries and so convert between them. Have a look in the `beziers/path/representations` directory for what I was trying to do. Anything that can implement `fromNodeList` and `toNodeList` can be converted. I don't know how that will interact with the Pen idea but it might be a start.

**Comment by justvanrossum** [comment]
The pen interface is not meant to be *the* way to deal with outlines, it's a lightweight protocol to transfer outlines from one object/format to another. It's almost like a wire protocol in that sense.

I'll have a look at `beziers/path/representations`. Sounds like you're trying to do the same thing that the pen protocol was designed for: easy exchange of bezier-based outline data between otherwise unrelated components.

**Comment by simoncozens** [comment]
Fair enough - I've seen people doing some very funny things with pens, then. :)

**Comment by justvanrossum** [comment]
It's often a sensible trade-off: either you implement some functionality on top of an existing path representation (creating a dependency) or build a pen-like object, using an ad-hoc internal representation. The latter approach has the advantage that it can be used anywhere where pens are supported, while having no additional dependencies.

It's not for everything, but the approach is extremely modular and has a very high reusability.
