### ISSUE TITLE
Obtaining path winding direction

### ISSUE THREAD

**Issue by takaakifuji** [simoncozens/beziers.py#13]
https://github.com/simoncozens/beziers.py/blob/a7bab2d1e80548a6775c06bfae8561ded115f379/beziers/path/__init__.py#L554-L562
As `beziers.path.BezierPath.area` discards signedness, the winding direction of a path cannot be obtained at the moment. The following are a selection of possible options:

1. Change `area()` so that it returns a negative value
2. Add a dedicated method, e.g. `GSPath.direction` or `defcon.Contour.clockwise`

I assume in most practical cases `beziers.path.BezierPath` is going to be constructed from GSPath (or via pen protocol), so obtaining direction can be easily done outside this library, but I think it would be a nice-to-have feature anyway. Just a suggestion.

**Comment by n8willis** [comment]
Concur that this would be useful. I'm using the package for non-Glyphs and non-Defcon analysis, and jumping through hoops to infer directionality can be costly.

Personally, I think a `.clockwise` property would be the more sensible approach. Returning a negative value for area is, so to speak, enforcing a set of constraints or assumptions after the fact. For example, when pulling things from binaries I can't assume that all contours are well-behaved and obey the cw/ccw rule they're supposed to (I'm also not 100% sure that composite glyphs are as well behaved). Besides, changing `area()` to return negatives could break existing code.

**Comment by ctrlcctrlv** [comment]
I echo the idea that we should not assume that people are going to be using proprietary software to interface with free software. I have used this library in a font of mine which did not do that. So a winding direction function would be very useful.

**Comment by simoncozens** [comment]
Ok, will do it!
