### ISSUE TITLE
More intersections trouble with thicknessAtX

### ISSUE THREAD

**Issue by n8willis** [simoncozens/beziers.py#17]
I have some pretty simple code that attempts to measure the thickness of a glyph using `thicknessAtX`, and it mysteriously returns `None` for some glyphs. It looks like means the function is finding less than two intersections, which shouldn't be possible.

The glyph has a bounding box of BB[<0.0,0.0> -> <744.8717358360673,247.18564455059698>] and is measuring at x=372.4358679180337 (that being halfway)....

It's a proprietary font (Minion Bold Italic as originally delivered on OSX), so I'm not sure I can legally post the full segment representation. But I would like to help debug this, so just tell me what else I can poke at. It is a single, closed contour. For contrast, the same function on the same glyph slot works 100% on Minion Italic. (Since this is another thicknessAtX / intersections issue, I suspect it's related to #14).

**Comment by simoncozens** [comment]
Can you post just the two segments that you should should intersect the line? Are either intersecting the line?

**Comment by ctrlcctrlv** [comment]
I really don't think there's any copyright issue with posting the outline of a single glyph. When a font is used in a PDF, you're distributing the outline of every glyph used in most cases.

It's not the same as distributing a full font. Wikipedia considers proprietary fonts used in SVGs to not be a copyright issue, as well.

**Comment by n8willis** [comment]
Well, it's clear in a font editor (which I would regard as an unbiased observer). If I have the code dump out the `.asSegments` representation of the glyph, it gives this: 
```
[B<<239.0,120.0>-<214.0,98.0>-<182.0,80.0>-<174.0,80.0>>, B<<174.0,80.0>-<168.0,80.0>-<166.0,91.0>-<172.0,119.0>>, B<<172.0,119.0>-<209.0,301.0>-<246.0,483.0>-<283.0,665.0>>, B<<283.0,665.0>-<289.0,693.0>-<287.0,703.0>-<274.0,703.0>>, B<<274.0,703.0>-<257.0,703.0>-<188.0,674.0>-<91.0,666.0>>, L<<91.0,666.0>--<85.0,636.0>>, L<<85.0,636.0>--<114.0,633.0>>, B<<114.0,633.0>-<154.0,630.0>-<158.0,623.0>-<147.0,570.0>>, B<<147.0,570.0>-<117.0,420.0>-<86.0,269.0>-<56.0,119.0>>, B<<56.0,119.0>-<33.0,9.0>-<53.0,-12.0>-<81.0,-12.0>>, B<<81.0,-12.0>-<116.0,-12.0>-<189.0,22.0>-<255.0,92.0>>, L<<255.0,92.0>--<239.0,120.0>>]
```
which is a tad more opaque, from my POV, for me to eyeball & say "yep, that's as expected". Though like I noted in the original comment, the bounding box is 100% easy to glance at and determine to be unmangled. So if something has gone off the rails in the representation, I'm not sure where.

**Comment by n8willis** [comment]
(For the record, this is a "l" (lowercase L) glyph, which is rotated 90° and translated to the origin, since we are out to measure the width at a given position, rather than the height.)

**Comment by simoncozens** [comment]
Thanks, that helps with debugging. It's finding the bottom intersection but not the top one. And this is line-line intersection, so it's very depressing that it's failing.

**Comment by n8willis** [comment]
Let me know if there's more I can do.

**Comment by simoncozens** [comment]
It's not line-line intersection, it's cubic-line intersection. Test case:

```python
s1 = CubicBezier.fromRepr("B<<584.0,126.03783241124995>-<402.0,163.0378324112499>-<220.00000000000003,200.03783241124995>-<38.0,237.03783241124995>>"),
ray = Line.fromRepr("L<<357.4,-9.99999999999999>--<357.6,250.2692949284206>>")

import matplotlib.pyplot as plt
fig, ax = plt.subplots()

BezierPath.fromSegments(s1).plot(ax)
BezierPath.fromSegments([ray]).plot(ax)
plt.show()

assert (s1[0].intersections(ray))
```

**Comment by simoncozens** [comment]
So we find the intersection by root-finding on the cubic. We know the t of the intersection on the cubic, and from there we can find the point. The problem comes when trying to find the t of that point on the line:

```python
In [7]: curve.pointAtTime(t)
Out[7]: <357.53991441925365,172.07642123810496>

In [13]: t_on_line = (point.x - line.start.x) / (line.end.x-line.start.x)

In [15]: t_on_line
Out[15]: 0.6995720962681958

In [16]: line.pointAtTime(t_on_line)
Out[16]: <357.53991441925365,172.0771362473205>

In [18]: line.pointAtTime(t_online).distanceFrom(point)
Out[18]: 0.0007150092155541188
```

That's pretty close, but it's not the same, and we do this in `line.py`:

```python
    if self.pointAtTime(t).distanceFrom(point) < 2e-7: return t
    return -1
```

I could change that arbitrary number to another arbitrary number and your code would work, but I would feel bad about it.

**Comment by simoncozens** [comment]
I've found a solution, I think. Please upgrade to 0.2.0.

**Comment by n8willis** [comment]
Thanks; will give it a thrashing shortly!
