### ISSUE TITLE
Path broken by change to fonttools

### ISSUE THREAD

**Issue by mhosken** [simoncozens/beziers.py#19]
path.fromFonttoolsGlyph now crashes due to refactoring in fonttools. Instead of:

Proposed new code
```
_glyph = font.getGlyphSet()[glyphname]
_glyph.draw(pen)
```

**Comment by bobh0303** [comment]
I think first sentence above was supposed to read:

> [path.fromFonttoolsGlyph](https://github.com/simoncozens/beziers.py/blob/5475e533d730ca900d5471496d406ebe80a15667/beziers/path/__init__.py#L120-L131) now crashes due to refactoring in fonttools. Instead of:
> 
> ```
>     _glyph = font.getGlyphSet()[glyphname]._glyph
>     if "glyf" in font:
>       _glyph.draw(pen, font["glyf"])
>     else:
>       _glyph.draw(pen)
> ```
