### ISSUE TITLE
Please add a way to stroke a Bezier spline with a pen that varies

### ISSUE THREAD

**Issue by ctrlcctrlv** [simoncozens/beziers.py#9]
![letter-powerstroke](https://user-images.githubusercontent.com/838783/92996349-c9375900-f4bf-11ea-8b58-a8c0f73f5bb2.gif)

**Comment by simoncozens** [comment]
Try this:

```
def brush(t): # 20pt 10˚ angled nib growing to 30pt at end of stroke
  b = Rectangle(20,5)
  b.rotate(Point(0,0),math.radians(10))
  b.scale(1+(1.5*t))
  return b

paths = shape.drawWithBrush(brush)
```

**Comment by ctrlcctrlv** [comment]
Hello, that is an implementation of a calligraphic pen:

![image](https://user-images.githubusercontent.com/838783/92998048-67c9b700-f4cc-11ea-8a21-13d7519a9943.png)

And not something like PowerStroke in Inkscape or Metapolator's thing. I only request it because when we talked about it on Twitter you said it'd be pretty easy to add. :-)

**Comment by simoncozens** [comment]
Notice the time t parameter in the brush function which makes the brush change size from start to end.

**Comment by ctrlcctrlv** [comment]
@simoncozens Ah ha! If I may, here's an example which more directly shows that this is not just calligraphy:

![image](https://user-images.githubusercontent.com/838783/93000469-8be1c400-f4dd-11ea-9611-60cc89eea17c.png)

No way to do that with a constant-width stroke :-)

```python3
def brush(t):
  print(t)
  b = Rectangle(80,80)
  b.rotate(Point(0,0),math.radians(10))
  # If it's 0 we will receive
  # AttributeError: 'MultiPolygon' object has no attribute 'exterior'
  b.scale(0.05+t)
  return b
```

I think this is exactly what I've been looking for 👀 let me play with it a bit more.

We really can get some quite fantastic results out:

![image](https://user-images.githubusercontent.com/838783/93000785-753c6c80-f4df-11ea-8972-1bb57828b491.png)

However, much slower than @skef's method if I hand it a `Circle`:

```python3
def brush(t):
  b = Circle(100)
  #b = Rectangle(100,100)
  b.rotate(Point(0,0),math.radians(10))
  # If it's 0 we will receive
  # AttributeError: 'MultiPolygon' object has no attribute 'exterior'
  if t > .5:
    t = .5-abs(t-.5)
  print(t)

  b.scale(0.11+t)
  return b
```

But can I really sit here and complain about _speed_ when I couldn't do this at all five minutes ago?

![image](https://user-images.githubusercontent.com/838783/93000819-a157ed80-f4df-11ea-800d-0deba5b47998.png)

To think I almost gave up on this library due to @simoncozens' example not being extreme enough and me not looking carefully enough!

**Comment by simoncozens** [comment]
I also suggest you call .tidy on the resulting paths.

**Comment by ctrlcctrlv** [comment]
Thanks @simoncozens , I'm planning to add this to Qstroke now. Unfortunately one provider doesn't do everything, and sometimes one provider fails when another doesn't, but yours will probably be the only provider that can do variable-width stroking. (The other providers will be libskef, @skef's addition to FontForge, and skia-pathops.)

I'm doing this provider-based method because math is not my strong suit at all :o)
